import type { Lesson, Resource } from '../types';

export const INITIAL_LESSONS: Lesson[] = [
  {
    id: 'lesson-2',
    lesson_number: 2,
    slug: 'thi-nhac',
    title: 'Thi nhạc',
    semester: 1,
    description: 'Truyện kể về cuộc thi âm nhạc của các loài vật trong khu rừng, giúp học sinh cảm thụ âm thanh cuộc sống và ý nghĩa của việc tôn trọng sự khác biệt.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-6',
    lesson_number: 6,
    slug: 'nghe-si-trong',
    title: 'Nghệ sĩ trống',
    semester: 1,
    description: 'Câu chuyện về chú dế muốn trở thành một nghệ sĩ trống giỏi, vượt qua khó khăn để cống hiến âm nhạc cho muôn loài.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-8',
    lesson_number: 8,
    slug: 'do-ngang',
    title: 'Đò ngang',
    semester: 1,
    description: 'Bài học ý nghĩa về lòng tốt, sự tận tụy thầm lặng của chiếc đò ngang qua sông đưa đón mọi người.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-10',
    lesson_number: 10,
    slug: 'tieng-noi-cua-co-cay',
    title: 'Tiếng nói của cỏ cây',
    semester: 1,
    description: 'Khám phá thế giới tự nhiên xung quanh qua lăng kính tưởng tượng phong phú, thấu hiểu tiếng nói thầm thì của các loài hoa lá.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-12',
    lesson_number: 12,
    slug: 'nha-phat-minh-6-tuoi',
    title: 'Nhà phát minh 6 tuổi',
    semester: 1,
    description: 'Truyện về sự tò mò khám phá và tinh thần khoa học của một bạn nhỏ 6 tuổi khi phát hiện ra cơ chế hoạt động thú vị.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-13',
    lesson_number: 13,
    slug: 'con-vet-xanh',
    title: 'Con vẹt xanh',
    semester: 1,
    description: 'Câu chuyện xúc động về tình yêu thương động vật và sự thấu cảm giữa người với vật qua hình ảnh chú vẹt xanh.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-16',
    lesson_number: 16,
    slug: 'truoc-ngay-xa-que',
    title: 'Trước ngày xa quê',
    semester: 1,
    description: 'Cảm xúc bồi hồi và những kỷ niệm thân thương của bạn nhỏ trước khi phải rời xa quê hương yêu dấu.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-25',
    lesson_number: 25,
    slug: 'bay-cung-uoc-mo',
    title: 'Bay cùng ước mơ',
    semester: 1,
    description: 'Gợi mở ước mơ bay cao, bay xa của trẻ thơ thông qua câu chuyện đầy cảm hứng sáng tạo.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-30',
    lesson_number: 30,
    slug: 'canh-chim-nho',
    title: 'Cánh chim nhỏ',
    semester: 1,
    description: 'Bài học ý nghĩa về sự tự do và tình yêu thương thiên nhiên hoang dã qua hình ảnh chú chim nhỏ.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-3-2',
    lesson_number: 3,
    slug: 'ong-but-da-den',
    title: 'Ông Bụt đã đến',
    semester: 2,
    description: 'Một câu chuyện cảm động mang màu sắc cổ tích hiện đại về lòng nhân ái, sự sẻ chia nâng đỡ những hoàn cảnh khó khăn.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-15-2',
    lesson_number: 15,
    slug: 'nguoi-thay-dau-tien-cua-bo-toi',
    title: 'Người thầy đầu tiên của bố tôi',
    semester: 2,
    description: 'Bài học sâu sắc về lòng tôn sư trọng đạo, tri ân người thầy đầu tiên qua ký ức của người cha.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'lesson-28-2',
    lesson_number: 28,
    slug: 'chuyen-du-lich-thu-vi',
    title: 'Chuyến du lịch thú vị',
    semester: 2,
    description: 'Cuộc hành trình kỳ thú mở ra những kiến thức địa lý và văn hóa bổ ích, thắp sáng trí tò mò của trẻ thơ.',
    thumbnail_url: null,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res-1',
    lesson_id: 'lesson-2',
    title: 'Video Bài học: Kịch bản âm nhạc của rừng xanh',
    resource_group: 'interactive_digital',
    resource_type: 'video',
    file_url: null,
    external_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Placeholder video
    description: 'Video giới thiệu các nhạc cụ tự nhiên và bài hát của muôn thú trong rừng.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-2',
    lesson_id: 'lesson-2',
    title: 'Phiếu học tập tương tác: Trắc nghiệm cảm thụ âm thanh',
    resource_group: 'interactive_digital',
    resource_type: 'interactive_worksheet',
    file_url: null,
    external_url: 'https://quizizz.com/join?gc=123456',
    description: 'Phiếu học tập tương tác thiết kế trên Quizizz giúp học sinh nhận diện giọng hát của các nhân vật.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-3',
    lesson_id: 'lesson-2',
    title: 'Podcast kể chuyện: Tiếng hát của ve sầu và chim họa mi',
    resource_group: 'reading_support',
    resource_type: 'podcast',
    file_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', // Free test mp3
    external_url: null,
    description: 'Podcast diễn cảm câu chuyện "Thi nhạc" với giọng đọc ấm áp giúp học sinh rèn luyện kỹ năng nghe.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-4',
    lesson_id: 'lesson-2',
    title: 'Phiếu bài tập trực quan: Vẽ sơ đồ dàn nhạc rừng xanh',
    resource_group: 'reading_support',
    resource_type: 'visual_worksheet',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', // Public dummy pdf
    external_url: null,
    description: 'Phiếu bài tập in ra PDF giúp học sinh nối các loài vật với nhạc cụ phù hợp.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-5',
    lesson_id: 'lesson-2',
    title: 'Kịch bản đóng vai: Ngày hội hòa nhạc rừng xanh',
    resource_group: 'teaching_model',
    resource_type: 'drama_script',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    external_url: null,
    description: 'Kịch bản phân vai ngắn cho 5 học sinh nhập vai các nhân vật: Vàng anh, Ve sầu, Dế mèn, Họa mi.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-6',
    lesson_id: 'lesson-2',
    title: 'Giáo án mẫu thiết kế bài dạy Đọc hiểu "Thi nhạc"',
    resource_group: 'teaching_model',
    resource_type: 'lesson_plan',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    external_url: null,
    description: 'Giáo án mẫu theo Công văn 2345 giúp giáo viên định hướng cách dạy bài đọc hiểu này.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Resource for lesson 6
  {
    id: 'res-7',
    lesson_id: 'lesson-6',
    title: 'Podcast: Câu chuyện về chú dế nghệ sĩ',
    resource_group: 'reading_support',
    resource_type: 'podcast',
    file_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    external_url: null,
    description: 'Audio podcast truyền cảm hứng về nghệ sĩ trống của rừng xanh.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Resource for lesson 8
  {
    id: 'res-8',
    lesson_id: 'lesson-8',
    title: 'Phiếu bài tập trực quan: Hành trình của Đò ngang',
    resource_group: 'reading_support',
    resource_type: 'visual_worksheet',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    external_url: null,
    description: 'Phiếu vẽ lại hành trình sông nước của Đò ngang và các hành khách.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Resource for lesson 3-2 (Ong but da den)
  {
    id: 'res-9',
    lesson_id: 'lesson-3-2',
    title: 'Video Bài học: Ông Bụt giữa đời thường',
    resource_group: 'interactive_digital',
    resource_type: 'video',
    file_url: null,
    external_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    description: 'Video phân tích giá trị nhân đạo của tác phẩm.',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
